### PR TITLE
Fix tags in generic order not expanded

### LINKED ISSUE #204: Generic: Order set can not expand author and date, etc.
# Description
**Generic: Order set can not expand author and date, etc.**

## Code example

```Cpp
"doxdocgen.generic.order": [
    "brief",
    "author",
    "date",
    "version",
    "param",
    "return",
]
```

### Expected result

```Cpp
/*
 * @brief Get the key alias object
 * @author author (email)
 * @date 2021-02-01
 * @version v0.1
 * @param 
 * @return 
 */

```

### Actual result

```Cpp
/*
 * @brief Get the key alias object
 * @param 
 * @return 
 */

```

### PR DESCRIPTION
**Pull request by HO-COOH**
# Fix/Feature/Other

## Fix

- [ ] Link to issue.
This closes #204 

- [ ] Description of the fix
~~Copied file-scoped tag branches -> generic tag branches, so it can be properly expanded.~~
The common tags that can be used in both `File` comments and `Method` comments are handled by one same function. So it can be both expanded properly.
genericTags

### CODE REVIEW

**Review by cschlosser — CHANGES_REQUESTED** [review]
I would prefer if we found a solution where we can reuse the already existing `generateCustomTag` method.

Otherwise the settings will be confusing and this breaks current functionality that people may rely on.

Maybe we have to make `generateCustomTag` smarter to replace what's possible but also insert tag's it doesn't have a replacement for.

**Comment by HO-COOH** [comment]
Cleaned up a little, and as you said `generateCustomTag()` is now reused.
I also moved those common tags that shared between `File` and `Method` to a separate function so easier to maintain, *hopefully*.

File: src/Lang/Cpp/CppDocGen.ts [hunk 1]
```diff
@@ -502,13 +508,11 @@ export class CppDocGen implements IDocGen {
...
                 case "custom": {
-                    this.cfg.Generic.customTags.forEach((elem) => {
-                        lines.push(this.getEnvVars(elem));
-                    });
+                    this.generateCustomTag(lines, CommentType.method);
                     break;
                 }
                 default: {
-                    break;
+                    this.generateCommonTag(lines, element);
```
Comment (cschlosser) [inline src/Lang/Cpp/CppDocGen.ts:515]: Can we let the default case still do nothing?

File: src/Lang/Cpp/CppDocGen.ts [hunk 2]
```diff
@@ -408,40 +446,16 @@ export class CppDocGen implements IDocGen {
...
-                    break;
-                }
                 case "custom": {
-                    this.generateCustomTag(lines);
+                    this.generateCustomTag(lines,CommentType.file);
                     break;
                 }
                 default: {
-                    break;
+                    this.generateCommonTag(lines, element);
```
Comment (cschlosser) [inline src/Lang/Cpp/CppDocGen.ts:458]: I would prefer leaving the default case empty. Otherwise typo's may show up with the custom tags which is probably not what de user expects.

**Review by cschlosser — COMMENTED** [review]
Thank you for extracting the shared one's. That's good I think.
Could you please take a look at CI so we can merge it?

File: src/Lang/Cpp/CppDocGen.ts (hunk 2 above)
Comment (HO-COOH) [reply src/Lang/Cpp/CppDocGen.ts:458]: That's handled in `generateCommonTag()`. There is a default break case there.

Comment (HO-COOH) [reply src/Lang/Cpp/CppDocGen.ts:458]: That's handled in `generateCommonTag()`. There is a default break case there.

**Comment by HO-COOH** [comment]
I see the error in CI comes from tslint. You might consider migrating to eslint. I am not very familiar with these toolings, just a suggestion :)

File: src/Lang/Cpp/CppDocGen.ts (hunk 2 above)
Comment (cschlosser) [reply src/Lang/Cpp/CppDocGen.ts:458]: My bad. I misread `generateCommonTag` as `generateCustomTag`.

**Review by cschlosser — COMMENTED** [review]
Looks good.
One more thing though. Could you please write a reproducer test for the bug?

You wrote here https://github.com/cschlosser/doxdocgen/issues/204#issuecomment-830499301 that `doxdocgen.generic.customTags` have to be removed from the config. This should no longer be true. Can we have a test for that as well please?

**Comment by HO-COOH** [comment]
> 
> 
> Looks good.
> One more thing though. Could you please write a reproducer test for the bug?
> 
> You wrote here [#204 (comment)](https://github.com/cschlosser/doxdocgen/issues/204#issuecomment-830499301) that `doxdocgen.generic.customTags` have to be removed from the config. This should no longer be true. Can we have a test for that as well please?

It's still true. He has duplicate tags in `generic.order` and `generic.customTags` such as `author` and `date` in the case. It's fine tho, if he really wants to include them twice. 

The change for this issue is that those variables in `generic.customTags` like `{date}` would be expanded in this PR.

**Comment by HO-COOH** [comment]
Added test case for this. And found and fixed another bug, that is if gitConfig is for user name and email is used, the custom tag with `{author}` and `{email}` will not be expanded properly, because your code is using `this.cfg.authorName` in the `getMultiTemplateString()`
